services:
  runner:
    environment:
      BENCH_ERRORCORE_CAPTURE_MODE: ${BENCH_ERRORCORE_CAPTURE_MODE}
      BENCH_ERRORCORE_LOCALS: ${BENCH_ERRORCORE_LOCALS}
      BENCH_ERRORCORE_MIDDLEWARE: ${BENCH_ERRORCORE_MIDDLEWARE}
